import './auth.routes';
import './dashboard.routes';
import './employees.routes';
import './attendance.routes';
import './sync.routes';
import './machines.routes';
import './quality.routes';
import './division.routes';
import './realtime.routes';
import './scheduler.routes';
import './import.routes';
import './alert.routes';
import './ops.routes';
import './monitoring.routes';
import './machine-employee.routes';
import './import-control.routes';

import './attendance-process.routes';
import './employees-comprehensive.routes';
